#!/usr/bin/env bash
# this scripts installs nginx on my server

apt-get -y update
apt-get -y install nginx
ufw allow 'nginx HTTP'
echo 'Hello World!' > /var/www/html/index.nginx-debian.html
service nginx start
