#!/usr/bin/env bash
# this scripts installs nginx on my server

apt-get -y update
apt-get -y install nginx
ufw allow 'nginx HTTP'
echo 'Hello World!' > /var/www/html/index.nginx-debian.html
sudo sed -i '/^}$/i \ \n\tlocation \/redirect_me {return 301 https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4 permanent;}' /etc/nginx/sites-available/default
sudo service nginx start
